#! /bin/csh
#
# Usage: checkAseg sub1 sub2 sub3

set bin = /home/camachocm2/Analysis/aggregate_anats/child_cortex/fs_scripts #path to bin
setenv SUBJECTS_DIR /moochie/Cat/Aggregate_anats/subjects_dir

foreach sub ($argv)

	echo "----------------------------------------------"
	echo
	echo "Checking automatic segmentation for "$sub
	echo
	freeview -viewport z -zoom 1.45 -v $SUBJECTS_DIR/$sub/mri/brainmask.mgz -v $SUBJECTS_DIR/$sub/mri/aseg.mgz:colormap=lut:lut=$bin/lut.txt:opacity=.17 & 
	echo
	echo "----------------------------------------------"

end
