#! /bin/csh -f

# Usage: run_recon23 subjectFolder [subjectFolder subjectFolder...]
# subjectFolder =  the subject's folder name (e.g. 001-T1). Multiple can be entered at once.

setenv SUBJECTS_DIR /home/camachocm2/Analysis/Aggregate_anats/tempSubjDir

foreach sub ($argv)

echo '****************************************************************** '
echo '****************************************************************** '
echo '******************* Working on subject '$sub'********************* '
echo '****************************************************************** '
echo '****************************************************************** '

recon-all -s $sub -autorecon2 -autorecon3 -parallel -openmp 4


echo '****************************************************************** '
echo '****************************************************************** '
echo '******************** finished subject '$sub'********************** '
echo '****************************************************************** '
echo '****************************************************************** '

cp -r $SUBJECTS_DIR/$sub /home/camachocm2/moochie/Cat/Aggregate_anats/subjects_dir

end
